### ISSUE TITLE
[top nav]: move top nav to have “Approach” start on fifth column

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#103]
@RyanCaruthers @alisonjoseph 
In xl breakpoint— "Teams" should be 7th column and "Practices" should be on 9th column and "Impact" on 11th column. The whole site goes to centered when larger than xl breakpoint. In theory, this should allow the type in the nav to align with type down the page.

Also, the IBM Design should be 32px from left edge when site is locked to the left side (see image just below)

![screen shot 2019-01-22 at 12 48 23 pm](https://user-images.githubusercontent.com/32881239/51555002-9bae1f80-1e44-11e9-9568-e2c3a25e1f89.png)

**Comment by mjabbink** [comment]
![screen shot 2019-01-22 at 12 48 41 pm](https://user-images.githubusercontent.com/32881239/51555010-a2d52d80-1e44-11e9-89af-507288f97a2f.png)

**Comment by mjabbink** [comment]
![screen shot 2019-01-22 at 12 48 56 pm](https://user-images.githubusercontent.com/32881239/51555019-a963a500-1e44-11e9-8ab9-b94a5c83f2f0.png)

**Comment by sadekbazaraa** [comment]
@RyanCaruthers @alisonjoseph

Mike and I were just discussing keeping the top nav centered along with the rest of the page elements when you expand past the max break point and extend the canvas. See attached.

![screen shot 2019-01-22 at 12 50 08 pm](https://user-images.githubusercontent.com/33162280/51555261-3d357100-1e45-11e9-896a-67797200801b.png)

**Comment by RyanCaruthers** [comment]
@sadekbazaraa Yeah i agree with this move. Lets do it!

**Comment by alisonjoseph** [comment]
Is this a change we want to be made across the global header component in regards to spacing. Currently, the header is not on the grid and expands to 100%. Where will the "X" sit at mobile? Tagging @jeanservaas since this will also affect the Carbon site. 

If the spacing is different, might seem weird jumping between sites?

**Comment by jeanservaas** [comment]
Talked to @sadekbazaraa about this and I would not want this to be a global change because Carbon has a left nav, whereas / design has a top nav. So I think the distinction could be that if you have a top nav, this could be the behavior and a left nav would function like IDL... and I don't think it would necessarily be weird to jump between.

I do think it's a problem for us to go max width with the header when the other sites like IDL and this one restrain the header width... I think whatever we do we wanna get on the same page about that.

**Comment by alisonjoseph** [comment]
This site currently goes 100% width, since it uses the same header as Carbon. It's not weird for one site to have padding-left of 32px and another 16px of the header text? (those numbers might be off)

**Comment by mjabbink** [comment]
I don't think weird if the reason why is clear. Margins can be variable but the primary goal is to maintain the integrity of the vertical alignment of type/elements aligning down a page along a column. The issue for slash design is logotype at 16px but ALL other type is 32px. So as you scroll the logos and content do not align. If we rock 32px in slash it will be clear as to why when a user scrolls and reads content. It will align. If they go to Carbon, it’s clear because the logotype aligns to the navigation text and it’s always open and the alignment is clear. I doubt they’ll even notice the margin change and if they did they will know why.

**Comment by mjabbink** [comment]
remember you’d only see this on a large display and browser opened up massively. In laptops it would be more subtle

**Comment by alisonjoseph** [comment]
Scheduled a meeting today w/ @jeanservaas and @RyanCaruthers to make sure I'm building this right 😅
