### ISSUE TITLE
EDT: copy, capitalization and tone

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/design-website#268]
EDT landing : https://design-website.netlify.com/approach/design-thinking 

## [EDT]: landing capitalization and tone

-->

Site currently says, "Enterprise design thinking" 
Should be a proper noun "Enterprise Design Thinking"

Tone: 
1. site into is: "Design thinking shouldn't be controversial..." sounds defensive. Why not something like, "We believe (or better yet) we know that design thinking is for everyone, whole teams relentlessly focused on creating better experiences for the people we serve."

2. The landing page for /design says the purpose of everything we do it to guide the people we serve
here on EDT it says 'everyone on the team should be focused on their users, first and foremost' at it simplest form, a change to "... the team should be focused on the people they serve" would align it with the landing and make it more human. 
DT, and more specifically EDT is yes about focusing on people, but it is just as much about collaboration and iteration. 

3. Tone, near the bottom it currently says, "Explore our framework and start driving better, user-centered outcomes for your business" ---> would be better to say "Try our framework and start driving better, human-centered outcomes at any scale"

**Comment by mbiyimoh** [comment]
@air2h2o thanks for the feedback! Will make sure to submit an edit for the EDT capitalization issue. My thoughts on the other three items:

1. I tend to agree with you on that...I think originally the intro was something like, "At its core, design thinking is simply the idea of putting human problems first." The language on the site now was a direct edit from Phil 
2. I like that. Will shoot a message to Maranda and Amanda to see if they're open to the idea of tweaking the language on the EDT site.
3. I like that edit. Will probably keep "explore" since the framework is a distinct and separate entity from the actual EDT coursework on the site (ie. you can explore the framework without committing to the platform right then and there), but I like "human-centered" over "user-centered" and "at any scale" is a good touch that hearkens back to the language at the beginning of the page about how EDT works for teams that are "widely dispersed".

Thanks for
